### ISSUE TITLE
Default Icons

### ISSUE THREAD

**Issue by scottsfarley93** [nataleedesotell/UWCL2.0#2]
Create icons for different documents types. For example, if the document is a pdf, we could have a paper icon.  If it's a multimedia file, we can have a different icon.  

If it is an image, we can do a visual preview of the document.  Having default icons will also lessen the data transfer load on mobile devices.

Data.gov uses a lot of icons for their different categories and for different file types.  For example: http://catalog.data.gov/dataset/demographic-statistics-by-zip-code-acfc9.

**Comment by nataleedesotell** [comment]
I added font-awesome.css, which has icons for PDF, images, video, etc. I may switch over to this for all other icons, too, because my initial font-awesome-ie7.css file is less comprehensive.

Examples of what's included: http://www.w3schools.com/icons/fontawesome_icons_filetype.asp
